### ISSUE TITLE
FlatFileOutputAdapter

### ISSUE THREAD

**Issue by skymania** [isparkes/OpenRate#3] opened 2015-06-19 12:57 UTC
I have been running the master branch on preproduction and I have noticed that FlatFileOutputAdapter
is broken. Thats to the fact that in master branch the communication from adapter and Transaction Manager, that we started and finished the file processing, has been removed.  

Calling super.procHeader(r) and super.procTrailer(r) is a must in their respective methods, except if you are planing to notify TM to finish in some other way?

**Comment by isparkes** [comment] 2015-06-20 09:17
It's been a bit more complicated since a few versions. The output adapter streams are closed by a separate thread (the "flusher thread"), and not directly any more from the transaction manager. This is to allow new transactions to start before long "commit" or "rollback" processing has been finished, say when we have to insert a batch of keys into a duplicate check table.

The way it is now is not very easy to understand, but gives advantages in performance (without it, we have a long "dead" period between streams).

This is software that is running in production all over the place, so I'd be surprised if it is badly broken. What *might* be the case is that the real time processing is not working with it (very few people use RT mode).

When you want to transfer from RT to batch mode, you need to use the TeeBatchConverter, and this rather esoteric module might well be broken.

If you can come up with a Maven project to demonstrate the problem, we'll fix it.

**Comment by skymania** [comment] 2015-06-20 16:33
Thank you for your fast reply and keep up the good work. I went over how Transaction Flusher works and thats the sole reason I opened this issue.

We never get to setClientStatus from FlatFileOutputAdapter anymore (removing casting done on 10. April caused that,  by removing super calls on procHeader and procTrailer. They are still present in 1.5.2.3 relase though) so we never get to put a transaction on transactionToFlushList and Transaction Flusher can't do any work on it.

If I'm wrong I apologize.

**Comment by isparkes** [comment] 2015-06-22 06:39
Yes, you look to be absolutely right. That is a genuine brainfart.

Let me run up a test case for that and we'll see about fixing it. I don't want to fix until proven broken, so please stick with v1.5.2.3 if you have production needs. (We don't have any production instances running on master - it is only recommended for the very adventurous).

**Comment by isparkes** [comment] 2015-06-22 08:10
Issue reproduced and repaired. Many thanks for your contribution!

**Comment by isparkes** [comment] 2015-06-22 08:10
Closed.

**Closed by isparkes** 2015-06-22 08:10 UTC
